allowBuilds:
  esbuild: true
  protobufjs: false
  unrs-resolver: true
minimumReleaseAge: 10080
saveExact: true
preferFrozenLockfile: true
minimumReleaseAgeExclude:
  - '@verdaccio/*'
  - 'verdaccio-*'
ignoreScripts: true
