name: Changesets

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
  NPM_CONFIG_PROVENANCE: 'true'

jobs:
  # Update package versions from changesets.
  version:
    timeout-minutes: 14
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.repository == 'verdaccio/verdaccio-google-cloud'
    steps:
      - name: checkout code repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version-file: '.nvmrc'
      - name: install pnpm
        run: |
          npm install --global corepack@latest
          corepack enable
          corepack install
      - name: install dependencies
        run: pnpm install
      - name: build
        run: pnpm build
      - name: create versions
        uses: changesets/action@63a615b9cd06ba9a3e6d13796c7fbcb080a60a0b
        with:
          version: pnpm ci:version
          commit: 'build: release packages'
          title: 'build: release packages'
          publish: pnpm ci:publish
          createGithubReleases: true
          setupGitUser: true
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESET_RELEASE_TOKEN }}
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org
